###
GET http://localhost:2500/api/v1/restaurant HTTP/1.1
content-type: application/json

###
###
POST http://localhost:2500/api/v1/restaurant HTTP/1.1
content-type: application/json

{
    "name": "name" ,
    "is_vegan": true ,
    "address": "addr" ,
    "owners_name": "woohyeon" 
}

###
PUT http://localhost:2500/api/v1/restaurant/18 HTTP/1.1
content-type: application/json

{
    "name": "without is vegan"
}

###
GET http://localhost:2500/api/v1/restaurant/11 HTTP/1.1
content-type: application/json

###

POST http://localhost:2500/api/v1/user/create HTTP/1.1
content-type: application/json

{
    "email": "test9@example.com",
	"password" : "test123!@#", 
	"password2": "test123!@#", 
	"role": "client2"
}